# echo 'bash aliases'
alias la='ls -a'
alias logout='qdbus org.kde.ksmserver /KSMServer logout 0 0 0'
alias ll='exa -alh'
alias vim='nvim'
alias top='bpytop'
alias fetch='~/scripts/fetch/fetch.sh'
alias clear='clear; colorscript --exec panes'
alias ..='cd ..'
alias ls='exa'
