# echo 'bash aliases'
alias la='ls -a'
alias logout='qdbus org.kde.ksmserver /KSMServer logout 0 0 0'
alias ll='exa -alh'
alias vim='nvim'
alias top='bpytop'
alias fetch='fastfetch --logo ~/.config/fastfetch/logos/littleGuy.png --logo-width 30 --logo-padding-top 2 --logo-padding-left 3'
alias clear='clear; colorscript --exec panes'
alias ..='cd ..'
alias ls='exa'
